FROM maven:3.8.3-openjdk-17

ARG UID=1000
ARG GID=1000

# Crea grupo solo si no existe, luego el usuario
RUN getent group $GID || groupadd -g $GID runner && \
    useradd -m -u $UID -g $GID runner

ENV MAVEN_CONFIG=/home/runner/.m2
WORKDIR /app

COPY pom.xml .
RUN mvn -B dependency:go-offline

COPY . .

RUN chown -R runner:runner /app

USER runner

CMD ["mvn", "-B", "--no-transfer-progress", "-Dmaven.clean.failOnError=false", "clean", "verify"]