FROM golang:1.22-alpine

ARG UID=1000
ARG GID=1000

RUN getent group $GID || addgroup -g $GID runner && \
    adduser -D -u $UID -G runner runner

WORKDIR /app
COPY go.mod ./
RUN go mod download
COPY . .
RUN chown -R runner:runner /app

USER runner

CMD ["go", "test", "-v", "./..."]

##docker build -f Dockerfile.test -t lp_test_logs:test .
