name: CD Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Ambiente destino'
        required: true
        type: choice
        options: [stage, production]
      image_tag:
        description: 'Tag de la imagen (ej: feature/test-a1b2c3d o develop-a1b2c3d o main-a1b2c3d)'
        required: true
        type: string

jobs:
  deploy:
    uses: maximilianomorero-lp/cicd-templates/.github/workflows/deploy.yml@main
    with:
      service_name: ${{ github.event.repository.name }}
      environment: ${{ inputs.environment }}
      image_tag: ${{ inputs.image_tag }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}