name: CD Deploy

on:
  workflow_dispatch:
    inputs:
      image_uri:
        description: 'URI completa de la imagen a deployar'
        required: true
        type: string

jobs:
  deploy:
    uses: maximilianomorero-lp/cicd-templates/.github/workflows/deploy.yml@main
    with:
      service_name: ${{ github.event.repository.name }}
      image_uri: ${{ inputs.image_uri }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}