name: CD Deploy

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Tag de la imagen a deployar (ej: develop-a1b2c3d)'
        required: true
        type: string
      environment:
        description: 'Ambiente destino'
        required: true
        type: choice
        options: [stage, production]

permissions:
  deployments: write

jobs:
  deploy:
    uses: maximilianomorero-lp/cicd-templates/.github/workflows/deploy.yml@main
    with:
      service_name: ${{ github.event.repository.name }}
      image_tag: ${{ inputs.image_tag }}
      environment: ${{ inputs.environment }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}