name: CI

on:
  pull_request:
    branches: [main, develop]
    types: [opened, synchronize, reopened]

jobs:
  tests:
    uses: maximilianomorero-lp/cicd-templates/.github/workflows/ci.yml@main
    with:
      service_name: ${{ github.event.repository.name }}
    # secrets:
    #   SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    #   SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

  claude-review:
    uses: maximilianomorero-lp/cicd-templates/.github/workflows/claude-pr-review.yml@main
    with:
      pr_number: ${{ github.event.pull_request.number }}
      base_ref: ${{ github.base_ref }}
      language: 'es'
    secrets:
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}

  build:
    needs: tests
    uses: maximilianomorero-lp/cicd-templates/.github/workflows/build.yml@main
    with:
      service_name: ${{ github.event.repository.name }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}